# Generated by Django 4.0.4 on 2022-06-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hazte_Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_documento', models.IntegerField(choices=[[0, 'Cedula'], [1, 'Pasaporte']])),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.IntegerField(choices=[[0, 'Casado/a'], [1, 'Soltero/a'], [2, 'Viudo/a'], [3, 'Separado/a'], [4, 'Union Libre'], [5, 'Divorciado/a']])),
                ('nacionalidad', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=10)),
                ('ocupacion', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=25)),
                ('provincia', models.CharField(max_length=25)),
            ],
        ),
    ]
