# Generated by Django 4.0.4 on 2022-06-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazte_socio', '0002_alter_hazte_socio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazte_socio',
            name='imagen_documento',
        ),
    ]
