# Generated by Django 4.0.4 on 2022-06-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazte_socio', '0003_remove_hazte_socio_imagen_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazte_socio',
            name='numero_cedula',
            field=models.CharField(max_length=11, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
