# Generated by Django 4.0.4 on 2022-06-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazte_socio', '0004_hazte_socio_numero_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazte_socio',
            old_name='numero_cedula',
            new_name='numero_documento',
        ),
        migrations.AddField(
            model_name='hazte_socio',
            name='imagen_documento',
            field=models.ImageField(null=True, upload_to='socios'),
        ),
    ]
