# Generated by Django 4.0.4 on 2022-06-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazte_socio', '0005_rename_numero_cedula_hazte_socio_numero_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazte_socio',
            name='imagen_documento',
        ),
    ]
