# Generated by Django 4.0.4 on 2022-06-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazte_socio', '0006_remove_hazte_socio_imagen_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazte_socio',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='hazte_socio',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Pendiente'], [1, 'Activo'], [2, 'Inactivo']], null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
