# Generated by Django 4.0.5 on 2022-07-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazte_socio', '0007_remove_hazte_socio_nacionalidad_hazte_socio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazte_socio',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='correo_electronico',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Pendiente'], [1, 'Activo'], [2, 'Inactivo']], null=b'I01\n', verbose_name='Estado '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='estado_civil',
            field=models.IntegerField(choices=[[0, 'Casado/a'], [1, 'Soltero/a'], [2, 'Viudo/a'], [3, 'Separado/a'], [4, 'Union Libre'], [5, 'Divorciado/a']], verbose_name='Estado Civil '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='numero_documento',
            field=models.CharField(max_length=11, null=b'I01\n', verbose_name='Número de Documento '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='ocupacion',
            field=models.CharField(max_length=25, verbose_name='Ocupación '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='provincia',
            field=models.CharField(max_length=25, verbose_name='Provincia '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='sector',
            field=models.CharField(max_length=25, verbose_name='Sector '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Teléfono '),
        ),
        migrations.AlterField(
            model_name='hazte_socio',
            name='tipo_documento',
            field=models.IntegerField(choices=[[0, 'Cedula'], [1, 'Pasaporte']], verbose_name='Tipo de Documento '),
        ),
    ]
